@WebApplication5_HostAddress = http://localhost:5090

GET {{WebApplication5_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApplication5_HostAddress}}/weatherforecast

###

GET {{WebApplication5_HostAddress}}/weatherforecast

###

GET {{WebApplication5_HostAddress}}/weatherforecast

###

GET {{WebApplication5_HostAddress}}/etudiant

###
